sonar.organization=i-robert2
sonar.projectKey=i-robert2_azure-m2-ghactions-aks
sonar.sources=app/api/src,app/frontend/src
sonar.exclusions=**/*.test.ts,**/dist/**,**/node_modules/**
sonar.tests=app/api/src
sonar.test.inclusions=**/*.test.ts
